// SPDX-FileCopyrightText: Copyright (c) 2026 realybin and contributors
// SPDX-License-Identifier: BSD-3-Clause

import type { ApiData } from "./api-types.js";
import { resolveApiVersion } from "./api-version.js";
import type { Context } from "./context.js";
import { NON_CLASS_BUILTIN_NAMES } from "./constants.js";
import { emitNativePrimitiveAliases } from "./native-primitive-types.js";
import { emitBuiltinClass, emitObjectClass } from "./emitters/class.js";
import { buildVariantUnion, emitGlobalScope, emitGodotModuleNamedExports } from "./emitters/misc.js";

export function generate(api: ApiData): string {
	const ctx: Context = {
		knownClassNames: new Set(api.classes.map((c) => c.name)),
		knownBuiltinNames: new Set(api.builtin_classes.map((b) => b.name)),
		emittedBuiltinNames: new Set(api.builtin_classes.map((b) => b.name).filter((name) => !NON_CLASS_BUILTIN_NAMES.has(name))),
		globalEnumNames: new Set(api.global_enums.map((enumDef) => enumDef.name)),
		precision: api.header?.precision,
	};

	const lines: string[] = [];
	lines.push("// AUTO-GENERATED FILE. DO NOT EDIT.");
	lines.push("// Generated by tools/puerts-godot-dts-gen from extension_api.json.");
	lines.push(`// api_version: ${resolveApiVersion(api)}`);
	lines.push("");
	lines.push("declare function load_type<T = any>(name: string): T;");
	lines.push("");
	lines.push('declare module "godot" {');
	lines.push("\tnamespace godot {");
	for (const line of emitNativePrimitiveAliases(ctx.precision)) {
		lines.push(`\t\t${line}`);
	}
	lines.push("");
	lines.push(`\t\ttype Variant = ${buildVariantUnion(ctx)};`);
	lines.push("\t\tfunction load_type<T = any>(name: String): T;");
	lines.push("");

	for (const line of emitGlobalScope(api, ctx)) {
		lines.push(`\t\t${line}`);
	}
	lines.push("");

	for (const builtin of api.builtin_classes) {
		if (NON_CLASS_BUILTIN_NAMES.has(builtin.name)) {
			continue;
		}
		for (const line of emitBuiltinClass(builtin, ctx)) {
			lines.push(`\t\t${line}`);
		}
		lines.push("");
	}

	for (const cls of api.classes) {
		for (const line of emitObjectClass(cls, ctx)) {
			lines.push(`\t\t${line}`);
		}
		lines.push("");
	}

	lines.push("\t}");
	lines.push("");
	lines.push("\texport const load_type: typeof globalThis.load_type;");
	for (const namedExportLine of emitGodotModuleNamedExports(api)) {
		lines.push(namedExportLine);
	}
	lines.push("}");
	lines.push("");
	lines.push('declare module "godot/*" {');
	lines.push("\tconst GodotType: any;");
	lines.push("\texport default GodotType;");
	lines.push("}");
	lines.push("");
	return `${lines.join("\n")}\n`;
}
